### ISSUE TITLE
Is there a demo or api manual for NLib.EventBus?

### ISSUE THREAD

**Issue by zwq000** [enbiso/Enbiso.NLib#8]
A brief look at the code, very clear, but how to use it? Is there some demo or manual?

**Comment by farajfarook** [comment]
@zwq000 I was using this project to my own projects so far and didn't bother creating documentation. As you show interest in it. I will start to look into it.

**Appsettings file**
```
{
  ...
  "EventBus": {
    "Servers": [ "nats://localhost:4222" ],
    "Client": "cuckoo.api",
    "Exchange": "cuckoo"
  }
}
```
**Startup.cs**
```
     services.AddEventBusNats(Configuration.GetSection("EventBus"));
     // Or use rabbitMQ or ServiceBus
     ....
     ....
     app.UseEventBus();
```

Then using `IEventService` publish the message

```
    await _eventService.PublishToBus(new MyCustomEvent
    {
                // Other properties
    });
```

Let me know if you need any further help.

**Comment by zwq000** [comment]
I like this library very much. They are very lightweight.  It's simple conventions reduce tedious configuration.
I tried to add Bson support for Eventbus or use protobuf as a serialization method.
Instead of using Json serialization in abstract, you might need separate abstract / provider interface support

Very thanks for your job

**Comment by farajfarook** [comment]
I will have a look at it. I'm more than happy to accept your PR if you can make it.
