### ISSUE TITLE
RabbitMqPersistentConnection Exception No ip address could be resolved for 192.168.3.103”

### ISSUE THREAD

**Issue by zwq000** [enbiso/Enbiso.NLib#9]
at RabbitMqPersistentConnection invoke
`_connection = _connectionFactory.CreateConnection();`
throw exception No ip address could be resolved for 192.168.3.103
but ip address is right, Appears only in Debug mode.
connection endpoint is asmq://192.168.3.103:6572

**Comment by farajfarook** [comment]
Pass the following parameters in appsettings
```
{
   "Server":  "192.168.3.103",
   "Port": "6572",
 ...
 ...
}
```
Refer the file https://github.com/enbiso/Enbiso.NLib/blob/master/Enbiso.NLib.EventBus.RabbitMq/RabbitMqOption.cs
for complete set of options that you can use.

**Comment by senglory** [comment]
Hi guys, I am experiencing exactly the same issue with RabbitMQ client v6.2.1 in my .NET Core 3.0 app. Many queues are consumed flawlessly but two to be used for sending messages throw this weird "No ip address could be resolved for XXX" even if I point a direct IP address instead of XXX. What's wrong with my ConnectionFactory definition? I don't work with Ipv6, it's 100% for sure. the failure happens on the last line in this code:

          ```
  System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            ConnectionFactory connectionFactory = new ConnectionFactory
            {
                AutomaticRecoveryEnabled = true,
                NetworkRecoveryInterval = new TimeSpan(0, 0, 0, 0, settings.NetworkRecoveryIntervalInMs),
                HostName = settings.Host,
                TopologyRecoveryEnabled = true,
                Ssl = settings.UseSSL ? new SslOption
                {
                    Enabled = true,
                    Version = System.Security.Authentication.SslProtocols.Tls12,
                    ServerName = settings.Host,
                    CertPath = settings.Cert,
                    CertPassphrase = settings.CertPassphrase,
                    AcceptablePolicyErrors = SslPolicyErrors.RemoteCertificateNameMismatch | SslPolicyErrors.RemoteCertificateChainErrors
                } : null,
                VirtualHost = settings.VirtualHost,
                Port = int.Parse(settings.Port),
                UserName = settings.UserName,
                Password = settings.Password
            };

            return connectionFactory.CreateConnection(settings.ClientName);
```
